### ISSUE TITLE
bower install sass-bootstrap not working

### ISSUE THREAD

**Issue by dilrajahdan** [jlong/sass-bootstrap-defunct#110]
I get the following error when trying to install sass-bootstrap via bower. 

any ideas? thanks.

`
$ bower install --save sass-bootstrap

bower cached        git://github.com/jlong/sass-twitter-bootstrap.git#2.3.2
bower validate      2.3.2 against git://github.com/jlong/sass-twitter-bootstrap.git#*
bower new           version for git://github.com/jlong/sass-twitter-bootstrap.git#*
bower resolve       git://github.com/jlong/sass-twitter-bootstrap.git#*
bower download      https://github.com/jlong/sass-twitter-bootstrap/archive/v3.0.0.tar.gz
bower extract       sass-bootstrap#\* archive.tar.gz
bower EACCES        EACCES, rename '/var/folders/fk/yx5x295x61b57pw7__h9_tlr0000gn/T/Dappa/bower/sass-bootstrap-2385-eQGGSL'

Stack trace:
Error: EACCES, rename '/var/folders/fk/yx5x295x61b57pw7__h9_tlr0000gn/T/Dappa/bower/sass-bootstrap-2385-eQGGSL'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:93:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at Promise.then.self.promiseDispatch.threw (/usr/local/lib/node_modules/bower/node_modules/q/q.js:834:30)
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at messages (/usr/local/lib/node_modules/bower/node_modules/q/q.js:574:44)

System info:
Bower version: 1.2.7
Node version: 0.8.12
OS: Darwin 11.4.2 x64
`

**Comment by alademann** [comment]
@dilrajahdan try using [my fork of bootstrap](https://github.com/alademann/sass-bootstrap) - you can install via `bower install sass-bootstrap-compass`

**Comment by jlong** [comment]
So one thing that has changed is we changed the name of the repo. Removed "twitter" to reflect the new naming of the boostrap project. That looks like it may be causing the error. Do we need to update the Bower registry somehow?

**Comment by Shipow** [comment]
it's working on my workspace. but when doing a 
    bower search sass-bootstrap

Search result is
    sass-bootstrap git://github.com/jlong/sass-twitter-bootstrap.git

So i guess that we have to figure out the way to rename the endpoint on bower server.

**Comment by jlong** [comment]
I submitted a request to get it renamed. No idea how long that will take. 

--John

**Comment by jednano** [comment]
Looks like it's legit now, updated 9 days ago.

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
