### ISSUE TITLE
npm install error with phantomjs

### ISSUE THREAD

**Issue by grayxr** [jlong/sass-bootstrap-defunct#124]
Here's the error:

> phantomjs@1.9.2-2 install /Users/jimmy/Sites/index.er/public/assets/sass-bootstrap/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

Downloading http://phantomjs.googlecode.com/files/phantomjs-1.9.2-macosx.zip
Saving to /Users/jimmy/Sites/index.er/public/assets/sass-bootstrap/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/phantomjs/phantomjs-1.9.2-macosx.zip
Receiving...
Error requesting archive
Phantom installation failed [Error: Error with http request: { 'content-type': 'text/html; charset="utf-8"' }] Error: Error with http request: { 'content-type': 'text/html; charset="utf-8"' }
    at ClientRequest.<anonymous> (/Users/jimmy/Sites/index.er/public/assets/sass-bootstrap/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:227:23)
    at ClientRequest.g (events.js:175:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)
    at Socket.socketOnData [as ondata](http.js:1583:20)
    at TCP.onread (net.js:525:27)
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by grayxr** [comment]
I updated 'patchwork' with composer and I think maybe that solved the issue.
